select

T.CODIGO_CADASTRO,
CAT.NOME as 'ASSOCIADO',
G.DESCRICAO as GRUPO,
A.DESCRICAO AS APLICACAO_FINANCEIRA,
T.DATA_EMISSAO,
T.DATA_VENCIMENTO,
(T.VALOR_TITULO + T.VALOR_ACRESCIMO - T.VALOR_DESCONTO) AS VALOR_TITULO,
cata.fantasia as UNIDADE, 
V.CODIGO, 
coalesce(V.DESCRICAO,'OUTROS') as DESCRICAO,
DATEDIFF(day,t.DATA_VENCIMENTO, GetDate()) as DIAS_ATRASADO,
T.PONTEIRO,
IFF.ID_SET,
IFF.ID_REGISTRATION AS PARENT,
'{}' as COOPERATIVA


from TITULO T
	
	INNER JOIN TITULO_MOVIMENTO TM ON TM.PONTEIRO = T.PONTEIRO
	AND TM.HISTORICO =1
	AND (TM.PONTEIRO_CONSOLIDADO IS NULL OR TM.PONTEIRO_CONSOLIDADO= 0)
	INNER JOIN CATALOGO CAT ON CAT.PESSOA = T.PESSOA
	AND CAT.CNPJ_CPF = T.CNPJ_CPF
	INNER JOIN APLICACAO_RECURSO_FINANCEIRO A ON T.CODIGO_APLICACAO_RECURSO_FIN = A.CODIGO
	AND T.CODIGO_EMPRESA = A.CODIGO_EMPRESA
	INNER JOIN GRUPO_APLIC_REC_FINANCEIRO G ON A.CODIGO_GRUPO = G.CODIGO
	AND G.CODIGO_EMPRESA = A.CODIGO_EMPRESA
	LEFT OUTER JOIN INVOICE_ITEM I ON TM.ID_TITULO_MOVIMENTO = I.ID_TITLE_MOVIMENT
	LEFT OUTER JOIN INVOICE IFF ON I.PARENT = IFF.ID
	LEFT OUTER JOIN INSURANCE_REG_SET IR ON IR.ID = IFF.ID_SET
	LEFT OUTER JOIN VENDEDOR V ON V.CODIGO = IR.ID_CONSULTANT
	LEFT JOIN silver.representante r ON r.codigo = iff.id_unity
	LEFT JOIN silver.catalogo cata ON cata.cnpj_cpf = r.cnpj_cpf


where DATEDIFF(day,t.DATA_VENCIMENTO, GetDate()) > 0
and t.CRC_CPG = 'R'


------------------------------------------------------------------------

union all

------------------------------------------------------------------------

select DISTINCT 

T.CODIGO_CADASTRO,
CAT.NOME,
G.DESCRICAO as GRUPO,
A.DESCRICAO AS APLICACAO,
T.DATA_EMISSAO,
T.DATA_VENCIMENTO,
(T.VALOR_TITULO + T.VALOR_ACRESCIMO - T.VALOR_DESCONTO) AS VALOR_TITULO,
cata.fantasia as UNIDADE,
V.CODIGO, 
coalesce(V.DESCRICAO,'OUTROS') as DESCRICAO,
DATEDIFF(day,t.DATA_VENCIMENTO, GetDate()) as DIAS_ATRASADO,
T.PONTEIRO,
IFF.ID_SET,
IFF.ID_REGISTRATION AS PARENT,
'{}' as COOPERATIVA


from TITULO T

	INNER JOIN TITULO_MOVIMENTO TM ON TM.PONTEIRO = T.PONTEIRO
	AND TM.HISTORICO =1
	INNER JOIN TITULO_MOVIMENTO TMC ON TMC.PONTEIRO_CONSOLIDADO = TM.PONTEIRO
	AND TMC.HISTORICO = 1
	INNER JOIN CATALOGO CAT ON CAT.PESSOA = T.PESSOA
	AND CAT.CNPJ_CPF = T.CNPJ_CPF
	INNER JOIN APLICACAO_RECURSO_FINANCEIRO A ON T.CODIGO_APLICACAO_RECURSO_FIN = A.CODIGO
	AND T.CODIGO_EMPRESA = A.CODIGO_EMPRESA
	INNER JOIN GRUPO_APLIC_REC_FINANCEIRO G ON A.CODIGO_GRUPO = G.CODIGO
	AND G.CODIGO_EMPRESA = A.CODIGO_EMPRESA
	LEFT OUTER JOIN INVOICE_ITEM I ON TMC.ID_TITULO_MOVIMENTO = I.ID_TITLE_MOVIMENT
	LEFT OUTER JOIN INVOICE IFF ON I.PARENT = IFF.ID
	LEFT OUTER JOIN INSURANCE_REG_SET IR ON IR.ID = IFF.ID_SET
	LEFT OUTER JOIN VENDEDOR V ON V.CODIGO = IR.ID_CONSULTANT
	LEFT JOIN silver.representante r ON r.codigo = iff.id_unity
	LEFT JOIN silver.catalogo cata ON cata.cnpj_cpf = r.cnpj_cpf


where DATEDIFF(day,t.DATA_VENCIMENTO, GetDate()) > 0
and t.CRC_CPG = 'R'
